version: '3.7'

services:
  nats:
    image: nats:latest
    container_name: nats
    ports:
      - "4222:4222"
      - "8222:8222"

  clickhouse-server:
    image: clickhouse/clickhouse-server
    hostname: clickhouse
    container_name: clickhouse
    environment:
      CLICKHOUSE_USER: clickhouse
      CLICKHOUSE_PASSWORD: 8123
    volumes:
      - ./app_clickhouse_data:/var/lib/clickhouse
    ports:
      - "8123:8123"
    depends_on:
      - nats